name: Bug Report
description: Report a bug to help us improve
title: '[BUG] '
labels: ['bug']
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Mobile
        - Web
    validations:
      required: true

  - type: dropdown
    id: application
    attributes:
      label: Application
      options:
        - B1
        - Lessons.church
        - Other
    validations:
      required: true

  - type: input
    id: other-app
    attributes:
      label: If Other, please specify
      placeholder: App name
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages (optional)
      description: If applicable, paste any error messages or logs here.
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: false

  - type: textarea
    id: church
    attributes:
      label: Church Name (optional)
      description: If comfortable, please provide your church name to help us with context.
    validations:
      required: false
